### ISSUE TITLE
hỏi thăm về dump

### ISSUE THREAD

**Issue by kelalung** [levisre/dotnettuts#1]
chào bạn, mình gặp tình trạng như sau
có 1 ứng dụng x64 code .net
trong code nó có chứa anti dumper + anti debug + check keygen online nữa, check sai thì ko cho chạy hàm tiếp theo
và giờ nó chơi thêm cái "themida 2x net" nữa
mình xem hướng dẫn unpack themida net trên mạng, có dùng megadump như ứng dụng này lại anti rồi,!
Ca này khó quá, bạn có hướng giải quyết nào ko?

**Comment by levisre** [comment]
Not related to Project's content
